### PR TITLE
Added eslint and automatically fixed linting issues

### PR DESCRIPTION
**Pull request by Uncleseneca**
#8

### CODE REVIEW

**Comment by igorkamyshev** [comment]
Thanks for PR. Great work. Please, fix some issues (check Telegram).

**Comment by Uncleseneca** [comment]
@igorkamyshev Hi!
A added separate repository with linting config
Please, take a look at this
https://github.com/Uncleseneca/eslint-config-solid-soda
https://www.npmjs.com/package/eslint-config-solid-soda

Actually, it's a Airbnb's base config ripoff, but we can change whatever we like))

**Comment by Uncleseneca** [comment]
Can you have a look at new updates?

**Comment by igorkamyshev** [comment]
Sure. Merge it. But I will publish new release after all issues for that will be closed.

**Pull request merged**
